workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - codemagic
      vars:
        XCODE_VERSION: "14.1"
        JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd app
          flutter pub get
      - name: Generate code
        script: |
          cd app
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: |
          cd app
          flutter build apk --release
    artifacts:
      - app/build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

