# Generated by Django 4.2.7 on 2025-11-15 17:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('emergency_contact_1', models.CharField(max_length=20)),
                ('emergency_contact_2', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('qr_code_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanner_info', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='emergency.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(choices=[('accident', 'Accident'), ('fire', 'Fire'), ('medical', 'Medical'), ('criminal', 'Criminal Activity'), ('disaster', 'Disaster')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('gps_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('gps_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='emergency.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
